steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Deployment Manifest'
    args: ['apply', '-f', 'infra/development/deploy/deployment.yml']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Service Manifest'
    args: ['apply', '-f', 'infra/development/deploy/service.yml']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Ingress Manifest'
    args: ['apply', '-f', 'infra/development/deploy/ingress.yml']
