steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: ['build', '-t', 'gcr.io/pretendland-firebase/countly:$SHORT_SHA', '.', '-f', 'Dockerfile-core']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to GCR'
    args: ['push', 'gcr.io/pretendland-firebase/countly:$SHORT_SHA']

options:
  machineType: 'N1_HIGHCPU_8'
